services:
  db:
    image: postgres:17
    container_name: database
    environment:
      - POSTGRES_USER=tp
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=gym
    ports:
      - "5432:5432"
    volumes:
      - ./psql_data:/var/lib/postgresql/data